export enum Message {
  Created = "Created",
  FieldRequired = "All fields required",
  ChooseDays = "You have to choose days number between 1-7",
  Updated = "Updated",
  TryAgain = "Error, try again",
  Deleted = "Deleted!",
  DidntFind = "Didnt find!",
  InvalidToken = "Invalid JWT Token",
  ExpiredToken = "Token expired",
  InputsMustBeNumbers = "Inputs must be numbers",
  NameIsRequired = "Name is required, and has to have minimum one character",
  EmailInvalid = "This email is not valid!",
  PasswordMin = "Passwword need to have minimum six characters",
  SamePassword = "Passwords need to be same",
  UserWithThatName = "We have user with that name",
  UserWithThatEmail = "We have user with that email",
  Unauthorized = "Unauthorized",
}
