import { StyleSheet } from "react-native";

export const CreateCurrentDayPlanStyles = StyleSheet.create({
    createCurrentDay:{
        height:'100%',
        width:'100%',
        position:'absolute',
        backgroundColor:'black',
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        zIndex:4
    },
    h2:{
        fontSize:30,
        textAlign:'center',
        width:'100%'
    },
    readyButton:{
        width:'30%',
        height:'8%',
        borderColor:'grey',
        borderWidth:2,
        borderRadius:5,
        display:'flex',
        justifyContent:'center',
        alignItems:'center',
        top:'5%'
    },
    exerciseHolder:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        width:'90%',
        marginTop:5
    },
    input:{
        borderRadius:10,
        height:30,
        fontSize:10,
        width:'30%',
        backgroundColor:'rgb(60,60,60)',
        paddingLeft:15
    },
    delete:{
        marginTop:'5%',
        position:'absolute',
        
    }
})