import { StyleSheet } from "react-native";

export const HistoryStyles=StyleSheet.create({
    historyContainer:{
        borderTopStartRadius:10,
        borderTopEndRadius:10,
        backgroundColor:'rgba(255,255,255,0.97)',
        height:'99%',
        width:'100%',
        zIndex:2
    },
    background:{
        height:'79%',
        width:'98%',
        marginLeft:'1%',
        marginRight:'1%',
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        opacity:1,
        resizeMode:'cover',
    },
    withoutTrainingContainer:{
        display:'flex',
        width:'100%',
        height:'50%',
        justifyContent:'center',
        alignItems:'center'
    },
    h1:{
        fontSize:40,
        textAlign:'center'
    },
    withoutTrainingText:{
        fontSize:20
    },
    session:{
        alignItems:'flex-start',
        borderWidth:3,
        borderColor:'grey',
        display:'flex',
        flexDirection:'column',
        justifyContent:'flex-start',
        position:'relative',
        marginTop:20,
        padding:2,
        width:'90%',
        borderRadius:10
    }
})