import { StyleSheet } from "react-native";

export const LoadingStyles = StyleSheet.create({
    loadingContainer:{
        backgroundColor:"rgb(19,19,19)",
        height:'100%',
        width:'100%',
        position:'absolute',
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        zIndex:6
    },
    logoLGYMAPP:{
        width:'70%',
        height:'40%'
    },
    loadingDiv:{
        display:'flex',
        flexDirection:'column',
        marginLeft:'5%',
        marginRight:'5%',
        marginTop:'40%',
        width:'90%'
    },
    loadingHolder:{
        borderWidth:2,
        borderColor:'grey',
        width:'100%',
        borderRadius:10,
        height:20,
    },
    loadingDivP:{
        fontSize:40,
        color:'white',
        textAlign:'center',
        width:'100%',
        marginTop:50
    }
})